# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'QRCode' do

pod 'CardIO'

end

target 'QRCodeTests' do

end

target 'QRCodeUITests' do

end

