# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'FM' do

pod 'Alamofire'
pod 'KGFloatingDrawer'
pod 'AFSoundManager'
pod 'KVNProgress'

end

target 'FMTests' do

end

target 'FMUITests' do

end

